export * from './src/entity.interface';
export * from './src/institute.interface';
export * from './src/jwt.interface';
export * from './src/practice-test.interface';
export * from './src/query-params.interface';
export * from './src/question.interface';
export * from './src/subject.interface';
export * from './src/topic.interface';
export * from './src/user.interface';
