-- CreateEnum
CREATE TYPE "ESubjectStatus" AS ENUM ('ACTIVE', 'PENDING_REVIEW', 'ARCHIVED');

-- AlterTable
ALTER TABLE "subjects" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "subjects" ADD COLUMN     "status" "ESubjectStatus" NOT NULL DEFAULT 'PENDING_REVIEW';
ALTER TABLE "subjects" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
